version = 1

exclude_patterns = ["foo.py", "foo/bar*.py", "baz.py"]
test_patterns = ["tests/"]

[[analyzers]]
name = "python"
enabled  = true
dependency_file_paths = ["requirements.txt"]
  [analyzers.meta]
  max_line_length = 10
  skip_doc_coverage = ["hello", "bar"]
  
